<p><label for="shipping_method_code">Code</label><br/>
<input id="shipping_method_code" name="shipping_method[code]" type="text" value="<?php echo $this->escape($shipping_method->code) ?>" size="10" /></p>

<p><label for="shipping_method_name">Name</label><br/>
<input id="shipping_method_name" name="shipping_method[name]" type="text" value="<?php echo $this->escape($shipping_method->name) ?>" size="35" /></p>