<p><label for="product_sku">SKU</label><br/>
<input id="product_sku" name="product[sku]" type="text" value="<?php echo $this->escape($product->sku) ?>" size="15" /></p>

<p><label for="product_price">Price</label><br/>
<input id="product_price" name="product[price]" type="text" value="<?php echo $this->escape($product->price) ?>" size="10" /></p>

<p><label for="product_name">Name</label><br/>
<input id="product_name" name="product[name]" type="text" value="<?php echo $this->escape($product->name) ?>" size="35" /></p>

<p><label for="product_description">Description</label><br/>
<textarea id="product_description" name="product[description]" rows="15" cols="35"><?php echo $this->escape($product->description) ?></textarea></p>