<?php echo $this->docType('XHTML1_STRICT') ?>
<html>
	<head>
		<?php echo $this->headTitle() ?>
		<script type="text/javascript" language="JavaScript" src="/js/prototype.js"></script>
		<style>
			body { padding: 0; margin: 0; background-color: #EEE; }
			
			h1 { font-size: 12pt; font-weight: bold; margin: 0, 1em; padding: 0; }
			h2 { font-size: 10pt; font-weight: bold; margin: 0, 1em; padding: 0; }
			
			a { text-decoration: none; color: blue; }
			a:visited { color: blue; }
			a:hover { color: red; }
			
			p, div, span, td { font-size: 8pt; }
			
			input, textarea { font-family: sans-serif; font-size: 8pt; }
			
			#nav { font-size: 10pt; position: absolute;top: 0;left: 0;right: 0;height: 20pt;padding: 0.5em; }
			#nav ul { padding: 0; margin: 0; display: inline; }
			#nav ul li { display: inline; list-style: none; }
			#nav a { text-decoration: none; color: blue; }
			#nav a:visited { color: blue; }
			#nav a:hover { color: red; }
			
			#content { position: absolute;top: 20pt;left: 0;right: 25%; padding: 1em; }
			
			#sidebar { position: absolute;top: 20pt;right: 0;left: 75%; }
		</style>
	</head>
	<body>
		
		<div id="nav">		
			<?php echo $this->layout()->nav ?>
		</div>
		
		<div id="content">
			<?php echo $this->layout()->content ?>
		</div>
		
		<div id="sidebar">
			<?php echo $this->layout()->sidebar ?>
		</div>
		
	</body>
</html>