<p><label for="shipping_method_code">Code</label><br/>
<input id="shipping_method_code" name="shipping_method[code]" type="text" value="<?php echo $this->escape($shipping_method->code) ?>" size="10" /></p>

<p><label for="shipping_method_description">Description</label><br/>
<input id="shipping_method_description" name="shipping_method[description]" type="text" value="<?php echo $this->escape($shipping_method->description) ?>" size="35" /></p>

<p><label for="shipping_method_shipper">Shipper</label><br/>
<input id="shipping_method_shipper" name="shipping_method[shipper]" type="text" value="<?php echo $this->escape($shipping_method->shipper) ?>" size="35" /></p>