<ul>
	<li><a href="/admin/category">Categories</a></li>
	<li><a href="/admin/customer">Customers</a></li>
	<li><a href="/admin/invoice">Invoices</a></li>
	<li><a href="/admin/manufacturer">Manufacturers</a></li>
	<li><a href="/admin/order">Orders</a></li>
	<li><a href="/admin/product">Products</a></li>
	<li><a href="/admin/shipment">Shipments</a></li>
	<li><a href="/admin/user">Users</a></li>
	<li><a href="/account/logout">Logout</a></li>
</ul>